#!/bin/sh


# Start all init scripts in /etc/init.d
# executing them in numerical order.
#
# S00-S98 按顺序启动
for i in /etc/init.d/S[0-8][0-9]* /etc/init.d/S9[0-8]* ;do

     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue

     case "$i" in
	*.sh)
	    # Source shell script for speed.
	    (
		trap - INT QUIT TSTP
		set start
		. $i
	    )
	    ;;
	*)
	    # No sh extension, so fork subprocess.
	    $i start
	    ;;
    esac
done

# S99 全部并行启动
for i in /etc/init.d/S99* ;do

     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue

     case "$i" in
	*.sh)
	    # Source shell script for speed.
	    (
		trap - INT QUIT TSTP
		set start
		. $i
	    ) &
	    ;;
	*)
	    # No sh extension, so fork subprocess.
	    $i start &
	    ;;
    esac
done
wait

