#!/bin/sh

start() {
    printf "Starting watchdogd: "
    # Start watchdogd in the background
    start-stop-daemon -S -b -n watchdogd -a /usr/sbin/watchdogd
    [ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
    printf "Stopping watchdogd: "
    start-stop-daemon -K -n watchdogd
    [ $? = 0 ] && echo "OK" || echo "FAIL"
}

restart() {
    stop
    sleep 1
    start
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|reload)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
