#!/bin/sh

setup_working_dir() {
    mkdir -p /etc/crontabs  /var/spool/cron/
    ln -s /etc/crontabs  /var/spool/cron/crontabs
}

start() {
    echo "Starting crontab: "
    setup_working_dir
    crond
    [ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
    killall crond
}

restart() {
    stop
    start
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|reload)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
