#!/bin/sh

DAEMON="connmand"
PIDFILE="/var/run/$DAEMON.pid"

CONNMAND_ARGS="-n"

# shellcheck source=/dev/null
[ -r "/etc/default/$DAEMON" ] && . "/etc/default/$DAEMON"

start() {
	if [ ! -d "/etc/kvmd/user/connman" ]; then
		mkdir -p /etc/kvmd/user/connman
	fi

	if [ ! -L "/var/lib/connman" ]; then
		ln -sf /etc/kvmd/user/connman /var/lib/connman
	fi

	# remove because we use inittab respawn to manage it now , this will conflict with inittab
	# printf 'Starting %s: ' "$DAEMON"
	# # shellcheck disable=SC2086 # we need the word splitting
	# start-stop-daemon -S -q -m -b -p "$PIDFILE" -x "/usr/sbin/$DAEMON" \
	# 	-- $CONNMAND_ARGS
	# status=$?
	# if [ "$status" -eq 0 ]; then
	# 	echo "OK"
	# else
	# 	echo "FAIL"
	# fi
	# return "$status"
}

stop() {
	echo
	# printf 'Stopping %s: ' "$DAEMON"
	# start-stop-daemon -K -q -p "$PIDFILE"
	# status=$?
	# if [ "$status" -eq 0 ]; then
	# 	echo "OK"
	# else
	# 	echo "FAIL"
	# fi
	# return "$status"
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
	start|stop|restart)
		"$1";;
	reload)
		# Restart, since there is no true "reload" feature.
		restart;;
	*)
		echo "Usage: $0 {start|stop|restart|reload}"
		exit 1
esac
