#! /bin/sh

NAME=ntpd
DAEMON=/usr/sbin/$NAME

# Gracefully exit if the package has been removed.
test -x $DAEMON || exit 0

# Read config file if it is present.
if [ -r /etc/default/$NAME ]
then
  . /etc/default/$NAME
fi

case "$1" in
  start)
    # 若用户持久化配置存在，升级后恢复
    if [ -f "/etc/kvmd/user/ntp.conf" ]; then
        cp -f "/etc/kvmd/user/ntp.conf" /etc/ntp.conf
    fi
    printf "Starting $NAME: "
    start-stop-daemon -S -q -x $DAEMON -- -g
    [ $? = 0 ] && echo "OK" || echo "FAIL"
    ;;
  stop)
    printf "Stopping $NAME: "
    start-stop-daemon -K -q -n $NAME
    [ $? = 0 ] && echo "OK" || echo "FAIL"
    ;;
  restart|reload)
    echo "Restarting $NAME: "
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload}" >&2
    exit 1
    ;;
esac

exit 0
