#!/bin/sh
# 
# Starts bluetoothd
#

start() {
    start-stop-daemon --start --quiet --pidfile /var/run/bluetoothd.pid --exec /usr/libexec/bluetooth/bluetoothd -- -C -E -d -n &
    if [ "$?" != "0" ] ; then
            echo "FAIL"
            return 1
    fi
    echo "OK"
}

stop() {
    start-stop-daemon --stop --quiet --pidfile /var/run/bluetoothd.pid
    if [ "$?" != "0" ] ; then
            echo "FAIL"
            return 1
    fi
    echo "OK"
}

restart() {
    stop
    start
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?