#!/bin/sh

[ -e /usr/sbin/ubusd ] || exit 0

case "$1" in
	start)
		printf "Starting ubusd: "
		start-stop-daemon -S -b -x /usr/sbin/ubusd
		[ $? = 0 ] && echo "OK" || echo "FAIL"
		;;
	stop)
		printf "Stopping ubusd: "
		start-stop-daemon -K -q -x /usr/sbin/ubusd
		[ $? = 0 ] && echo "OK" || echo "FAIL"
		;;
	restart|reload)
		$0 stop
		$0 start
		;;
	*)
		echo "Usage: "${0}d" {start|stop|restart}"
		exit 1
esac

exit 0
