#!/bin/sh

exit 0 # temporary disable

start() {
    printf "Starting kvmd-rndis: "
    /usr/sbin/kvmd-rndis start
    [ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
    printf "Stopping kvmd-rndis: "
    /usr/sbin/kvmd-rndis stop
    [ $? = 0 ] && echo "OK" || echo "FAIL"
}

restart() {
    stop
    sleep 1
    start
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|reload)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
